---
title: "Curriculum"
output: html_document
---

<!-----
---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
----->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!------------ Intro ------------------>
## Programming

### Automation

- Q1: What is the most annoying & repetitive task at work? 
- Q2: How could you automate it? 

Programming is essentially an automation of a process
- for repeatable tasks (like adding two numbers)
- scalable (many times repeating )
- complicated tasks (variable selection)
- where precision is needed (adding two decimals)
- reusing of frameworks (long code into functions)
- reproduce it

A side effect of a certain automation also brings reproducibility. 

### Functions and libraries

Programming typically works like this: you apply a function to an object. 

You could also say that you apply an action (a verb) to an object (a noun). 

Excel also has functions: these are the tabs, and the object would be your active sheet. 

This is an important propertiy, because a chain of such verbs can create a programming script. 

If you hear the term library or package, then this is simply a collection of functions. In opensource languages, anyone can contribute a package. And we will do this later. 

### What we expect from a language

- Reproducible
- used by many people...
- high or low level

### R 

Now, we are here to learn together the bits and pieces of data analysis in R. 

Why are we using R? 

Basically, you could use any language that satisfies all the criteria that we ahve specified before. For example Python or even somethign lower level. 

But R is tailored to statistical data analysis. It has been developed to do statistical data analysis, and moreover to let peers have insight into data.

Effortless data analysis and sharing of results.

While at the beginning 20 years ago it was mainly plotting and modelling, now it is large scale, accessible, ...  

It can 

There are things R is good at and tasks that R is not that good at. And this has changed over time. Because R is an open source project, the language is constantly evolving & improving. 

Rstudio is a UI to R. It is a company. 


### What can R do? 
Ask for keywords

### R has three things that I believe makes it special

- APIs
- RMarkdown
- Plotting, anything visual

See [workshop](#workshop).

### APIs
- APIs: opensnp (rsnps), https://rviews.rstudio.com/2018/07/23/rest-apis-and-plumber/
- SPSS to R: https://twitter.com/phillynerd/status/1130633179134607360?s=09

### functions and packages in R 

Example with plot: function, arguments, pacakage, libraary, objects



<!------------------ -------------------->
## Data analysis

Steps and cycle of an analysis: 

import > analysis > output

### Example

R has become very good in output (shiny, html, websites, ... )

video, animation, presentation, website, write to excel

### Fun examples
- https://www.hvitfeldt.me/blog/circle-love-making-hearts-with-circles/
- https://twitter.com/AmeliaMN/status/1126891572807729152?s=09
- sports science: https://jacquietran.github.io/2019_may_rladies_akl/R/#1
- ggplot2: https://cedricscherer.netlify.com/2019/05/17/the-evolution-of-a-ggplot-ep.-1/
- research compendium: 
    - https://github.com/seabbs/DirectEffBCGPolicyChange
    - https://github.com/venexia/MR-antihypertensives-AD
    - https://github.com/saralpulit/fatdistnGWAS
    

<!---------- ------------------>

## How do you learn a new language while also learning statistics? 

- Learn isolated / digestable pieces
- surroud yourself with the language
- create fun examples
- learn
- community / use blogposts and write blogposts

### COmmunity

- ropensci
- R4DS
- R-Ladies
- R forwards
- join a meetup!
- https://ropensci.shinyapps.io/contributr/
- french slack: - https://r-grrr.slack.com/join/shared_invite/enQtMzI4MzgwNTc4OTAxLWZlOGZiZTBiMWU0NDQ3OTYzOGE1YThiODgwZWNhNWEyYjI4ZDJiNmNhY2YyYWI5YzFiOTFkNDYxYzkwODUwNWM
- RUG
- satRdays
- code of conduct


<!---------- ------------------>

## Best practices

- what does _best practices_ mean? like best practices in the lab. works without, but safer. 
- what does best pracices encompass? grammar, folder structure, ...


Help you making things reproducible 

there is a landscape of best practices, has a hierarchy. 

- documentation
- unit tests and sanity checks
- version control
- write functions and package them and tell everyone
- continuous integration
- run all script
- makefile (caching)


(reference: ...)

### Documentation

Make example

Comments
structure (align, lintr)

How much documentation do you need? 

Example: look at an old script and reformat.

### Colors
- https://nanx.me/ggsci/


### Data import

janitor
skimr
readr
data.table

### dsf 

### How to ask questions? 

reprex

### Run your code on another computer

- Think about your future self
- Add simple instructions and ask a colleague to do it

### Pair programming

code review and programm together

### Git

You use git already: congratulations. 

You want to use git but you are scared: 
- use the interface
- use gist.github.com (great for blogposts and small scripts)


<!------------ ---------------->
## Workshop


### 1. Plotting + model


#### Task
Change something on the plot

#### Extra
look into plotly, animation



### 2. Make a map

#### Task
Change pin location

#### Extra
make a leaflet with watercolors


### 3. Import data

Rexcel

#### Task
import other data

#### extra
different r packages to import data: readr, data.table


### 4. Rmarkdown
export as html, combine 1 + 2 + 3

#### Task
export as pdf

#### Extra

Look into xaringan and CSS file



### 5. R package

create a package with corporate colors EPFL: https://www.epfl.ch/campus/services/communication/wp-content/uploads/2019/03/EPFL-brand-guidelines.pdf

#### Task

Add an extra color 

#### Extra 
Add your own function



### 6. Extra stuff

- Shiny
- collaborative writing
- 


## Workshop

