---
title: "Tick report"
author: Sina
date: "2019-02-07 (updated: `r Sys.Date()`)" 
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: true
    highlight: tango

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Put it in context with the data analysis workflow. 

# Import data


```{r}

## https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-04-02
bike_traffic <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-02/bike_traffic.csv")

## https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-05-14
nobel_winners <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv")

## https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-06-11
meteorites <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")

library(ggplot2)
ggplot(data = meteorites) + geom_point(aes(long, lat))



## make a map

library(ggplot2)
library(dplyr)
require(maps)
require(viridis)
theme_set(
  theme_void()
  )

## basic
world_map <- map_data("world")
ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill="lightgray", colour = "white") + 
  geom_point(data = meteorites, aes(long, lat), color="red", alpha=0.5)

## color as year
world_map <- map_data("world")
ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill="lightgray", colour = "white") + 
  geom_point(data = meteorites, aes(long, lat, color = year), alpha=0.5)


## make an annimation
library(gganimate)
world_map <- map_data("world")
ggplot(data = meteorites) +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill="lightgray", colour = "white") + 
  geom_point(data = meteorites, aes(long, lat), color="red", alpha=0.5) + 
  transition_manual(year)  +
  labs(title = "Date: {frame}") +
  NULL


```

# Data preparation
- use janitor + skimr


# Descriptive analysis


# Map

```{r cars, echo=FALSE}
summary(cars)
```

```{r pressure, echo=FALSE}
plot(pressure)
```

## store out

```{r}
#as xlsx

#library(xlsx)
#write.xlsx(data_sm, file = glue::glue("{DIR_DESCRIPT}/ms_tables.xlsx"),
##           sheetName = "Table 1 (data summary)", append = FALSE, showNA=FALSE, row.names = FALSE) 
#write.xlsx(res_sm, file = glue::glue("{DIR_DESCRIPT}/ms_tables.xlsx"),
#           sheetName = "Table 2 (results summary)", append = TRUE, showNA=FALSE, row.names = FALSE)


#library( writexl)
#?write_xlsx
#tmp <- write_xlsx(list(mysheet = iris))
#readxl::read_xlsx(tmp)

#as csv
```

# Exercise

- export as pdf/word/markdown
- 

## Extra

- Look into xaringan and CSS file
- code download button: https://twitter.com/apreshill/status/1108925218850893832


# More infos

- https://rmd4sci.njtierney.com/
- rmarkdown: https://holtzy.github.io/Pimp-my-rmd/

